- hosts: dev_groups
  sudo: yes
  roles:
    - common
    - database
    - app

- name: Provision an EC2 node
  hosts: local
  connection: local
  gather_facts: False
  tags: provisioning
  vars:
    instance_type: t1.micro
    security_group: sg_web
    image: ami-a73264ce
    region: us-east-1
    keypair: ec2lab
  tasks:
    - name: Launch new Instance
      ec2: >
        instance_tags="Name=AnsibleTest"
        group={{ security_group }}
        instance_type={{ instance_type}}
        image={{ image }} wait=true
        region={{ region }}
        keypair={{ keypair }}
      register: ec2
    - name: Add instance to local host group
      add_host: hostname={{ item.public_ip }} groupname=ec2hosts
      # local_action: lineinfile dest=hosts regexp="{{ item.public_dns_name }}" insertafter="[launched]" line="{{ item.public_dns_name }} ansible_ssh_private_key_file=~/.ssh/{{ keypair }}.pem"
      with_items: ec2.instances
    - name: Wait for SSH to come up
      local_action: wait_for host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances
      register: pause
